repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'  # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-django
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.3' # Update me!
    hooks:
      - id: bandit